import type { PriceReferenceInput } from '../../shared/types'

export const SEED_PRICE_REFERENCES: PriceReferenceInput[] = [
  {
    product_name: 'Lucky Me Pancit Canton Original 60g',
    brand: 'Lucky Me',
    barcode: '4800016644810',
    unit: 'pack',
    market_price_c: 1050,
    min_price_c: 900,
    max_price_c: 1500,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Lucky Me Pancit Canton Kalamansi 60g',
    brand: 'Lucky Me',
    barcode: '4800016644827',
    unit: 'pack',
    market_price_c: 1050,
    min_price_c: 900,
    max_price_c: 1500,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Lucky Me Pancit Canton Extra Hot Chili 60g',
    brand: 'Lucky Me',
    barcode: '4800016644841',
    unit: 'pack',
    market_price_c: 1050,
    min_price_c: 900,
    max_price_c: 1500,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Lucky Me Beef Mami 55g',
    brand: 'Lucky Me',
    barcode: '4800016644612',
    unit: 'pack',
    market_price_c: 1000,
    min_price_c: 850,
    max_price_c: 1300,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Lucky Me Chicken Mami 55g',
    brand: 'Lucky Me',
    barcode: '4800016644629',
    unit: 'pack',
    market_price_c: 1000,
    min_price_c: 850,
    max_price_c: 1300,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Mega Sardines in Tomato Sauce 155g',
    brand: 'Mega',
    barcode: '4800049720017',
    unit: 'can',
    market_price_c: 2400,
    min_price_c: 2200,
    max_price_c: 2800,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: '555 Sardines in Tomato Sauce 155g',
    brand: '555',
    barcode: '4800092110018',
    unit: 'can',
    market_price_c: 2250,
    min_price_c: 2000,
    max_price_c: 2600,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Bear Brand Fortified Powdered Milk 33g',
    brand: 'Bear Brand',
    barcode: '4800361301015',
    unit: 'sachet',
    market_price_c: 1500,
    min_price_c: 1300,
    max_price_c: 1800,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Nescafe Classic Single 2g',
    brand: 'Nescafe',
    barcode: '4800361280013',
    unit: 'sachet',
    market_price_c: 450,
    min_price_c: 400,
    max_price_c: 600,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Kopiko Brown Coffee Twin Pack 53g',
    brand: 'Kopiko',
    barcode: '8996001303120',
    unit: 'twin pack',
    market_price_c: 1300,
    min_price_c: 1200,
    max_price_c: 1600,
    currency: 'PHP',
    source_name: 'Market Price Guide',
    source_type: 'market',
    location: 'Philippines',
    effective_date: '2026-02-01'
  },
  {
    product_name: 'Great Taste White Coffee Twin Pack 50g',
    brand: 'Great Taste',
    barcode: '4800016650019',
    unit: 'twin pack',
    market_price_c: 1250,
    min_price_c: 1100,
    max_price_c: 1500,
    currency: 'PHP',
    source_name: 'Market Price Guide',
    source_type: 'market',
    location: 'Philippines',
    effective_date: '2026-02-01'
  },
  {
    product_name: 'Coca-Cola Mismo 290ml',
    brand: 'Coca-Cola',
    barcode: '4801981110012',
    unit: 'bottle',
    market_price_c: 1500,
    min_price_c: 1500,
    max_price_c: 2000,
    currency: 'PHP',
    source_name: 'Market Price Guide',
    source_type: 'market',
    location: 'Philippines',
    effective_date: '2026-02-01'
  },
  {
    product_name: 'Coca-Cola 1.5L PET',
    brand: 'Coca-Cola',
    barcode: '4801981110029',
    unit: 'bottle',
    market_price_c: 7500,
    min_price_c: 7000,
    max_price_c: 8500,
    currency: 'PHP',
    source_name: 'Market Price Guide',
    source_type: 'market',
    location: 'Philippines',
    effective_date: '2026-02-01'
  },
  {
    product_name: 'Datu Puti Soy Sauce 385ml',
    brand: 'Datu Puti',
    barcode: '4801668601011',
    unit: 'pouch',
    market_price_c: 2100,
    min_price_c: 1900,
    max_price_c: 2500,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Datu Puti Vinegar 385ml',
    brand: 'Datu Puti',
    barcode: '4801668601028',
    unit: 'pouch',
    market_price_c: 1850,
    min_price_c: 1600,
    max_price_c: 2200,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Silver Swan Soy Sauce 385ml',
    brand: 'Silver Swan',
    barcode: '4800038101018',
    unit: 'pouch',
    market_price_c: 2050,
    min_price_c: 1850,
    max_price_c: 2450,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Safeguard Pure White Bar Soap 60g',
    brand: 'Safeguard',
    barcode: '4902430740012',
    unit: 'bar',
    market_price_c: 2600,
    min_price_c: 2400,
    max_price_c: 3000,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'Surf Powder Sun Fresh 55g',
    brand: 'Surf',
    barcode: '4800888140019',
    unit: 'sachet',
    market_price_c: 950,
    min_price_c: 850,
    max_price_c: 1200,
    currency: 'PHP',
    source_name: 'DTI Suggested Retail Price',
    source_type: 'official',
    source_url: 'https://www.dti.gov.ph/konsyumer/suggested-retail-price-srp/',
    location: 'Philippines',
    effective_date: '2026-01-15'
  },
  {
    product_name: 'San Miguel Pale Pilsen 330ml',
    brand: 'San Miguel',
    barcode: '4800012111013',
    unit: 'bottle',
    market_price_c: 5500,
    min_price_c: 5000,
    max_price_c: 6500,
    currency: 'PHP',
    source_name: 'Market Price Guide',
    source_type: 'market',
    location: 'Philippines',
    effective_date: '2026-02-01'
  },
  {
    product_name: 'Red Horse Beer 500ml',
    brand: 'Red Horse',
    barcode: '4800012111020',
    unit: 'bottle',
    market_price_c: 6500,
    min_price_c: 6000,
    max_price_c: 7500,
    currency: 'PHP',
    source_name: 'Market Price Guide',
    source_type: 'market',
    location: 'Philippines',
    effective_date: '2026-02-01'
  }
]
